/*
 * Resources and endpoints
 * When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AdditionalFieldsMapInnerInner;
import com.konfigthis.client.model.AdditionalFilesMapInner;
import com.konfigthis.client.model.AttachmentRequestsMapInner;
import com.konfigthis.client.model.CopiedContactsMapInner;
import com.konfigthis.client.model.TemplateFieldsMapInner;
import com.konfigthis.client.model.TemplateRecipientsMapInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DocumentFromTemplateRequest
 */
public class DocumentFromTemplateRequestTest {
    private final DocumentFromTemplateRequest model = new DocumentFromTemplateRequest();

    /**
     * Model tests for DocumentFromTemplateRequest
     */
    @Test
    public void testDocumentFromTemplateRequest() {
        // TODO: test DocumentFromTemplateRequest
    }

    /**
     * Test the property 'testMode'
     */
    @Test
    public void testModeTest() {
        // TODO: test testMode
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    public void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'templateIds'
     */
    @Test
    public void templateIdsTest() {
        // TODO: test templateIds
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'recipients'
     */
    @Test
    public void recipientsTest() {
        // TODO: test recipients
    }

    /**
     * Test the property 'draft'
     */
    @Test
    public void draftTest() {
        // TODO: test draft
    }

    /**
     * Test the property 'withSignaturePage'
     */
    @Test
    public void withSignaturePageTest() {
        // TODO: test withSignaturePage
    }

    /**
     * Test the property 'expiresIn'
     */
    @Test
    public void expiresInTest() {
        // TODO: test expiresIn
    }

    /**
     * Test the property 'reminders'
     */
    @Test
    public void remindersTest() {
        // TODO: test reminders
    }

    /**
     * Test the property 'applySigningOrder'
     */
    @Test
    public void applySigningOrderTest() {
        // TODO: test applySigningOrder
    }

    /**
     * Test the property 'apiApplicationId'
     */
    @Test
    public void apiApplicationIdTest() {
        // TODO: test apiApplicationId
    }

    /**
     * Test the property 'embeddedSigning'
     */
    @Test
    public void embeddedSigningTest() {
        // TODO: test embeddedSigning
    }

    /**
     * Test the property 'embeddedSigningNotifications'
     */
    @Test
    public void embeddedSigningNotificationsTest() {
        // TODO: test embeddedSigningNotifications
    }

    /**
     * Test the property 'textTags'
     */
    @Test
    public void textTagsTest() {
        // TODO: test textTags
    }

    /**
     * Test the property 'customRequesterName'
     */
    @Test
    public void customRequesterNameTest() {
        // TODO: test customRequesterName
    }

    /**
     * Test the property 'customRequesterEmail'
     */
    @Test
    public void customRequesterEmailTest() {
        // TODO: test customRequesterEmail
    }

    /**
     * Test the property 'redirectUrl'
     */
    @Test
    public void redirectUrlTest() {
        // TODO: test redirectUrl
    }

    /**
     * Test the property 'allowDecline'
     */
    @Test
    public void allowDeclineTest() {
        // TODO: test allowDecline
    }

    /**
     * Test the property 'allowReassign'
     */
    @Test
    public void allowReassignTest() {
        // TODO: test allowReassign
    }

    /**
     * Test the property 'declineRedirectUrl'
     */
    @Test
    public void declineRedirectUrlTest() {
        // TODO: test declineRedirectUrl
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'templateFields'
     */
    @Test
    public void templateFieldsTest() {
        // TODO: test templateFields
    }

    /**
     * Test the property 'files'
     */
    @Test
    public void filesTest() {
        // TODO: test files
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'attachmentRequests'
     */
    @Test
    public void attachmentRequestsTest() {
        // TODO: test attachmentRequests
    }

    /**
     * Test the property 'copiedContacts'
     */
    @Test
    public void copiedContactsTest() {
        // TODO: test copiedContacts
    }

}
