/*
 * Resources and endpoints
 * When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MeGetAccountInfoResponseAccountActiveUsersInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MeGetAccountInfoResponseAccount
 */
public class MeGetAccountInfoResponseAccountTest {
    private final MeGetAccountInfoResponseAccount model = new MeGetAccountInfoResponseAccount();

    /**
     * Model tests for MeGetAccountInfoResponseAccount
     */
    @Test
    public void testMeGetAccountInfoResponseAccount() {
        // TODO: test MeGetAccountInfoResponseAccount
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'planTier'
     */
    @Test
    public void planTierTest() {
        // TODO: test planTier
    }

    /**
     * Test the property 'activeTemplates'
     */
    @Test
    public void activeTemplatesTest() {
        // TODO: test activeTemplates
    }

    /**
     * Test the property 'canCreateTemplate'
     */
    @Test
    public void canCreateTemplateTest() {
        // TODO: test canCreateTemplate
    }

    /**
     * Test the property 'canCreateTrackingDocument'
     */
    @Test
    public void canCreateTrackingDocumentTest() {
        // TODO: test canCreateTrackingDocument
    }

    /**
     * Test the property 'canCreateCompletionDocument'
     */
    @Test
    public void canCreateCompletionDocumentTest() {
        // TODO: test canCreateCompletionDocument
    }

    /**
     * Test the property 'activeUsers'
     */
    @Test
    public void activeUsersTest() {
        // TODO: test activeUsers
    }

}
