/*
 * Resources and endpoints
 * When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TemplateGetTemplateDataResponseCopiedPlaceholdersInner;
import com.konfigthis.client.model.TemplateGetTemplateDataResponseFieldsInnerInner;
import com.konfigthis.client.model.TemplateGetTemplateDataResponseFilesInner;
import com.konfigthis.client.model.TemplateGetTemplateDataResponsePlaceholdersInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TemplateGetTemplateDataResponse
 */
public class TemplateGetTemplateDataResponseTest {
    private final TemplateGetTemplateDataResponse model = new TemplateGetTemplateDataResponse();

    /**
     * Model tests for TemplateGetTemplateDataResponse
     */
    @Test
    public void testTemplateGetTemplateDataResponse() {
        // TODO: test TemplateGetTemplateDataResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'archived'
     */
    @Test
    public void archivedTest() {
        // TODO: test archived
    }

    /**
     * Test the property 'embeddedEditUrl'
     */
    @Test
    public void embeddedEditUrlTest() {
        // TODO: test embeddedEditUrl
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'requesterEmailAddress'
     */
    @Test
    public void requesterEmailAddressTest() {
        // TODO: test requesterEmailAddress
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'templateLink'
     */
    @Test
    public void templateLinkTest() {
        // TODO: test templateLink
    }

    /**
     * Test the property 'allowDecline'
     */
    @Test
    public void allowDeclineTest() {
        // TODO: test allowDecline
    }

    /**
     * Test the property 'allowReassign'
     */
    @Test
    public void allowReassignTest() {
        // TODO: test allowReassign
    }

    /**
     * Test the property 'apiApplicationId'
     */
    @Test
    public void apiApplicationIdTest() {
        // TODO: test apiApplicationId
    }

    /**
     * Test the property 'declineRedirectUrl'
     */
    @Test
    public void declineRedirectUrlTest() {
        // TODO: test declineRedirectUrl
    }

    /**
     * Test the property 'expiresIn'
     */
    @Test
    public void expiresInTest() {
        // TODO: test expiresIn
    }

    /**
     * Test the property 'redirectUrl'
     */
    @Test
    public void redirectUrlTest() {
        // TODO: test redirectUrl
    }

    /**
     * Test the property 'reminders'
     */
    @Test
    public void remindersTest() {
        // TODO: test reminders
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'applySigningOrder'
     */
    @Test
    public void applySigningOrderTest() {
        // TODO: test applySigningOrder
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'files'
     */
    @Test
    public void filesTest() {
        // TODO: test files
    }

    /**
     * Test the property 'copiedPlaceholders'
     */
    @Test
    public void copiedPlaceholdersTest() {
        // TODO: test copiedPlaceholders
    }

    /**
     * Test the property 'placeholders'
     */
    @Test
    public void placeholdersTest() {
        // TODO: test placeholders
    }

}
