/*
 * Resources and endpoints
 * When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BulkSendListBulkSendingsResponseBulkSendsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * BulkSendListBulkSendingsResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class BulkSendListBulkSendingsResponse {
  public static final String SERIALIZED_NAME_BULK_SENDS = "bulk_sends";
  @SerializedName(SERIALIZED_NAME_BULK_SENDS)
  private List<BulkSendListBulkSendingsResponseBulkSendsInner> bulkSends = null;

  public static final String SERIALIZED_NAME_CURRENT_PAGE = "current_page";
  @SerializedName(SERIALIZED_NAME_CURRENT_PAGE)
  private Double currentPage;

  public static final String SERIALIZED_NAME_NEXT_PAGE = "next_page";
  @SerializedName(SERIALIZED_NAME_NEXT_PAGE)
  private String nextPage;

  public static final String SERIALIZED_NAME_PREVIOUS_PAGE = "previous_page";
  @SerializedName(SERIALIZED_NAME_PREVIOUS_PAGE)
  private String previousPage;

  public static final String SERIALIZED_NAME_TOTAL_COUNT = "total_count";
  @SerializedName(SERIALIZED_NAME_TOTAL_COUNT)
  private Double totalCount;

  public static final String SERIALIZED_NAME_TOTAL_PAGES = "total_pages";
  @SerializedName(SERIALIZED_NAME_TOTAL_PAGES)
  private Double totalPages;

  public BulkSendListBulkSendingsResponse() {
  }

  public BulkSendListBulkSendingsResponse bulkSends(List<BulkSendListBulkSendingsResponseBulkSendsInner> bulkSends) {
    
    
    
    
    this.bulkSends = bulkSends;
    return this;
  }

  public BulkSendListBulkSendingsResponse addBulkSendsItem(BulkSendListBulkSendingsResponseBulkSendsInner bulkSendsItem) {
    if (this.bulkSends == null) {
      this.bulkSends = new ArrayList<>();
    }
    this.bulkSends.add(bulkSendsItem);
    return this;
  }

   /**
   * Get bulkSends
   * @return bulkSends
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<BulkSendListBulkSendingsResponseBulkSendsInner> getBulkSends() {
    return bulkSends;
  }


  public void setBulkSends(List<BulkSendListBulkSendingsResponseBulkSendsInner> bulkSends) {
    
    
    
    this.bulkSends = bulkSends;
  }


  public BulkSendListBulkSendingsResponse currentPage(Double currentPage) {
    
    
    
    
    this.currentPage = currentPage;
    return this;
  }

  public BulkSendListBulkSendingsResponse currentPage(Integer currentPage) {
    
    
    
    
    this.currentPage = currentPage.doubleValue();
    return this;
  }

   /**
   * Get currentPage
   * @return currentPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "")

  public Double getCurrentPage() {
    return currentPage;
  }


  public void setCurrentPage(Double currentPage) {
    
    
    
    this.currentPage = currentPage;
  }


  public BulkSendListBulkSendingsResponse nextPage(String nextPage) {
    
    
    
    
    this.nextPage = nextPage;
    return this;
  }

   /**
   * Get nextPage
   * @return nextPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNextPage() {
    return nextPage;
  }


  public void setNextPage(String nextPage) {
    
    
    
    this.nextPage = nextPage;
  }


  public BulkSendListBulkSendingsResponse previousPage(String previousPage) {
    
    
    
    
    this.previousPage = previousPage;
    return this;
  }

   /**
   * Get previousPage
   * @return previousPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPreviousPage() {
    return previousPage;
  }


  public void setPreviousPage(String previousPage) {
    
    
    
    this.previousPage = previousPage;
  }


  public BulkSendListBulkSendingsResponse totalCount(Double totalCount) {
    
    
    
    
    this.totalCount = totalCount;
    return this;
  }

  public BulkSendListBulkSendingsResponse totalCount(Integer totalCount) {
    
    
    
    
    this.totalCount = totalCount.doubleValue();
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5", value = "")

  public Double getTotalCount() {
    return totalCount;
  }


  public void setTotalCount(Double totalCount) {
    
    
    
    this.totalCount = totalCount;
  }


  public BulkSendListBulkSendingsResponse totalPages(Double totalPages) {
    
    
    
    
    this.totalPages = totalPages;
    return this;
  }

  public BulkSendListBulkSendingsResponse totalPages(Integer totalPages) {
    
    
    
    
    this.totalPages = totalPages.doubleValue();
    return this;
  }

   /**
   * Get totalPages
   * @return totalPages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "")

  public Double getTotalPages() {
    return totalPages;
  }


  public void setTotalPages(Double totalPages) {
    
    
    
    this.totalPages = totalPages;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BulkSendListBulkSendingsResponse instance itself
   */
  public BulkSendListBulkSendingsResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkSendListBulkSendingsResponse bulkSendListBulkSendingsResponse = (BulkSendListBulkSendingsResponse) o;
    return Objects.equals(this.bulkSends, bulkSendListBulkSendingsResponse.bulkSends) &&
        Objects.equals(this.currentPage, bulkSendListBulkSendingsResponse.currentPage) &&
        Objects.equals(this.nextPage, bulkSendListBulkSendingsResponse.nextPage) &&
        Objects.equals(this.previousPage, bulkSendListBulkSendingsResponse.previousPage) &&
        Objects.equals(this.totalCount, bulkSendListBulkSendingsResponse.totalCount) &&
        Objects.equals(this.totalPages, bulkSendListBulkSendingsResponse.totalPages)&&
        Objects.equals(this.additionalProperties, bulkSendListBulkSendingsResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulkSends, currentPage, nextPage, previousPage, totalCount, totalPages, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkSendListBulkSendingsResponse {\n");
    sb.append("    bulkSends: ").append(toIndentedString(bulkSends)).append("\n");
    sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
    sb.append("    nextPage: ").append(toIndentedString(nextPage)).append("\n");
    sb.append("    previousPage: ").append(toIndentedString(previousPage)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bulk_sends");
    openapiFields.add("current_page");
    openapiFields.add("next_page");
    openapiFields.add("previous_page");
    openapiFields.add("total_count");
    openapiFields.add("total_pages");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BulkSendListBulkSendingsResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!BulkSendListBulkSendingsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BulkSendListBulkSendingsResponse is not found in the empty JSON string", BulkSendListBulkSendingsResponse.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("bulk_sends") != null && !jsonObj.get("bulk_sends").isJsonNull()) {
        JsonArray jsonArraybulkSends = jsonObj.getAsJsonArray("bulk_sends");
        if (jsonArraybulkSends != null) {
          // ensure the json data is an array
          if (!jsonObj.get("bulk_sends").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `bulk_sends` to be an array in the JSON string but got `%s`", jsonObj.get("bulk_sends").toString()));
          }

          // validate the optional field `bulk_sends` (array)
          for (int i = 0; i < jsonArraybulkSends.size(); i++) {
            BulkSendListBulkSendingsResponseBulkSendsInner.validateJsonObject(jsonArraybulkSends.get(i).getAsJsonObject());
          };
        }
      }
      if (!jsonObj.get("next_page").isJsonNull() && (jsonObj.get("next_page") != null && !jsonObj.get("next_page").isJsonNull()) && !jsonObj.get("next_page").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `next_page` to be a primitive type in the JSON string but got `%s`", jsonObj.get("next_page").toString()));
      }
      if (!jsonObj.get("previous_page").isJsonNull() && (jsonObj.get("previous_page") != null && !jsonObj.get("previous_page").isJsonNull()) && !jsonObj.get("previous_page").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `previous_page` to be a primitive type in the JSON string but got `%s`", jsonObj.get("previous_page").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BulkSendListBulkSendingsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BulkSendListBulkSendingsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BulkSendListBulkSendingsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BulkSendListBulkSendingsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<BulkSendListBulkSendingsResponse>() {
           @Override
           public void write(JsonWriter out, BulkSendListBulkSendingsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public BulkSendListBulkSendingsResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             BulkSendListBulkSendingsResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BulkSendListBulkSendingsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BulkSendListBulkSendingsResponse
  * @throws IOException if the JSON string is invalid with respect to BulkSendListBulkSendingsResponse
  */
  public static BulkSendListBulkSendingsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BulkSendListBulkSendingsResponse.class);
  }

 /**
  * Convert an instance of BulkSendListBulkSendingsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

