/*
 * Resources and endpoints
 * When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DocumentSendReminderResponseCopiedContactsInner;
import com.konfigthis.client.model.DocumentSendReminderResponseFieldsInnerInner;
import com.konfigthis.client.model.DocumentSendReminderResponseFilesInner;
import com.konfigthis.client.model.DocumentSendReminderResponseMetadata;
import com.konfigthis.client.model.DocumentSendReminderResponseRecipientsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DocumentSendReminderResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DocumentSendReminderResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_ARCHIVED = "archived";
  @SerializedName(SERIALIZED_NAME_ARCHIVED)
  private Boolean archived;

  public static final String SERIALIZED_NAME_EMBEDDED_EDIT_URL = "embedded_edit_url";
  @SerializedName(SERIALIZED_NAME_EMBEDDED_EDIT_URL)
  private String embeddedEditUrl;

  public static final String SERIALIZED_NAME_EMBEDDED_PREVIEW_URL = "embedded_preview_url";
  @SerializedName(SERIALIZED_NAME_EMBEDDED_PREVIEW_URL)
  private String embeddedPreviewUrl;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_REQUESTER_EMAIL_ADDRESS = "requester_email_address";
  @SerializedName(SERIALIZED_NAME_REQUESTER_EMAIL_ADDRESS)
  private String requesterEmailAddress;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_TEST_MODE = "test_mode";
  @SerializedName(SERIALIZED_NAME_TEST_MODE)
  private Boolean testMode;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_ERROR_MESSAGE = "error_message";
  @SerializedName(SERIALIZED_NAME_ERROR_MESSAGE)
  private String errorMessage;

  public static final String SERIALIZED_NAME_DECLINE_MESSAGE = "decline_message";
  @SerializedName(SERIALIZED_NAME_DECLINE_MESSAGE)
  private String declineMessage;

  public static final String SERIALIZED_NAME_ALLOW_DECLINE = "allow_decline";
  @SerializedName(SERIALIZED_NAME_ALLOW_DECLINE)
  private Boolean allowDecline;

  public static final String SERIALIZED_NAME_ALLOW_REASSIGN = "allow_reassign";
  @SerializedName(SERIALIZED_NAME_ALLOW_REASSIGN)
  private Boolean allowReassign;

  public static final String SERIALIZED_NAME_API_APPLICATION_ID = "api_application_id";
  @SerializedName(SERIALIZED_NAME_API_APPLICATION_ID)
  private String apiApplicationId;

  public static final String SERIALIZED_NAME_CUSTOM_REQUESTER_EMAIL = "custom_requester_email";
  @SerializedName(SERIALIZED_NAME_CUSTOM_REQUESTER_EMAIL)
  private String customRequesterEmail;

  public static final String SERIALIZED_NAME_CUSTOM_REQUESTER_NAME = "custom_requester_name";
  @SerializedName(SERIALIZED_NAME_CUSTOM_REQUESTER_NAME)
  private String customRequesterName;

  public static final String SERIALIZED_NAME_DECLINE_REDIRECT_URL = "decline_redirect_url";
  @SerializedName(SERIALIZED_NAME_DECLINE_REDIRECT_URL)
  private String declineRedirectUrl;

  public static final String SERIALIZED_NAME_EMBEDDED_SIGNING = "embedded_signing";
  @SerializedName(SERIALIZED_NAME_EMBEDDED_SIGNING)
  private Boolean embeddedSigning;

  public static final String SERIALIZED_NAME_EXPIRES_IN = "expires_in";
  @SerializedName(SERIALIZED_NAME_EXPIRES_IN)
  private Double expiresIn;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private DocumentSendReminderResponseMetadata metadata;

  public static final String SERIALIZED_NAME_REDIRECT_URL = "redirect_url";
  @SerializedName(SERIALIZED_NAME_REDIRECT_URL)
  private String redirectUrl;

  public static final String SERIALIZED_NAME_REMINDERS = "reminders";
  @SerializedName(SERIALIZED_NAME_REMINDERS)
  private Boolean reminders;

  public static final String SERIALIZED_NAME_APPLY_SIGNING_ORDER = "apply_signing_order";
  @SerializedName(SERIALIZED_NAME_APPLY_SIGNING_ORDER)
  private Boolean applySigningOrder;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private String subject;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<List<DocumentSendReminderResponseFieldsInnerInner>> fields = null;

  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private List<DocumentSendReminderResponseFilesInner> files = null;

  public static final String SERIALIZED_NAME_COPIED_CONTACTS = "copied_contacts";
  @SerializedName(SERIALIZED_NAME_COPIED_CONTACTS)
  private List<DocumentSendReminderResponseCopiedContactsInner> copiedContacts = null;

  public static final String SERIALIZED_NAME_RECIPIENTS = "recipients";
  @SerializedName(SERIALIZED_NAME_RECIPIENTS)
  private List<DocumentSendReminderResponseRecipientsInner> recipients = null;

  public DocumentSendReminderResponse() {
  }

  public DocumentSendReminderResponse id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "9334554b-b023-4883-9fe3-dc9d764992c5", value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public DocumentSendReminderResponse archived(Boolean archived) {
    
    
    
    
    this.archived = archived;
    return this;
  }

   /**
   * Get archived
   * @return archived
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getArchived() {
    return archived;
  }


  public void setArchived(Boolean archived) {
    
    
    
    this.archived = archived;
  }


  public DocumentSendReminderResponse embeddedEditUrl(String embeddedEditUrl) {
    
    
    
    
    this.embeddedEditUrl = embeddedEditUrl;
    return this;
  }

   /**
   * Get embeddedEditUrl
   * @return embeddedEditUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmbeddedEditUrl() {
    return embeddedEditUrl;
  }


  public void setEmbeddedEditUrl(String embeddedEditUrl) {
    
    
    
    this.embeddedEditUrl = embeddedEditUrl;
  }


  public DocumentSendReminderResponse embeddedPreviewUrl(String embeddedPreviewUrl) {
    
    
    
    
    this.embeddedPreviewUrl = embeddedPreviewUrl;
    return this;
  }

   /**
   * Get embeddedPreviewUrl
   * @return embeddedPreviewUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://www.signwell.com/preview/document/9334554b-b023-4883-9fe3-dc9d764992c5/", value = "")

  public String getEmbeddedPreviewUrl() {
    return embeddedPreviewUrl;
  }


  public void setEmbeddedPreviewUrl(String embeddedPreviewUrl) {
    
    
    
    this.embeddedPreviewUrl = embeddedPreviewUrl;
  }


  public DocumentSendReminderResponse name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "distant-message/error.js", value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public DocumentSendReminderResponse requesterEmailAddress(String requesterEmailAddress) {
    
    
    
    
    this.requesterEmailAddress = requesterEmailAddress;
    return this;
  }

   /**
   * Get requesterEmailAddress
   * @return requesterEmailAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "cousin_nicky_12@example.com", value = "")

  public String getRequesterEmailAddress() {
    return requesterEmailAddress;
  }


  public void setRequesterEmailAddress(String requesterEmailAddress) {
    
    
    
    this.requesterEmailAddress = requesterEmailAddress;
  }


  public DocumentSendReminderResponse status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Sent", value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }


  public DocumentSendReminderResponse testMode(Boolean testMode) {
    
    
    
    
    this.testMode = testMode;
    return this;
  }

   /**
   * Get testMode
   * @return testMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getTestMode() {
    return testMode;
  }


  public void setTestMode(Boolean testMode) {
    
    
    
    this.testMode = testMode;
  }


  public DocumentSendReminderResponse createdAt(String createdAt) {
    
    
    
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2024-02-12T13:16:14Z", value = "")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    
    
    
    this.createdAt = createdAt;
  }


  public DocumentSendReminderResponse updatedAt(String updatedAt) {
    
    
    
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2024-02-12T13:16:15Z", value = "")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    
    
    
    this.updatedAt = updatedAt;
  }


  public DocumentSendReminderResponse errorMessage(String errorMessage) {
    
    
    
    
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getErrorMessage() {
    return errorMessage;
  }


  public void setErrorMessage(String errorMessage) {
    
    
    
    this.errorMessage = errorMessage;
  }


  public DocumentSendReminderResponse declineMessage(String declineMessage) {
    
    
    
    
    this.declineMessage = declineMessage;
    return this;
  }

   /**
   * Get declineMessage
   * @return declineMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDeclineMessage() {
    return declineMessage;
  }


  public void setDeclineMessage(String declineMessage) {
    
    
    
    this.declineMessage = declineMessage;
  }


  public DocumentSendReminderResponse allowDecline(Boolean allowDecline) {
    
    
    
    
    this.allowDecline = allowDecline;
    return this;
  }

   /**
   * Get allowDecline
   * @return allowDecline
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getAllowDecline() {
    return allowDecline;
  }


  public void setAllowDecline(Boolean allowDecline) {
    
    
    
    this.allowDecline = allowDecline;
  }


  public DocumentSendReminderResponse allowReassign(Boolean allowReassign) {
    
    
    
    
    this.allowReassign = allowReassign;
    return this;
  }

   /**
   * Get allowReassign
   * @return allowReassign
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getAllowReassign() {
    return allowReassign;
  }


  public void setAllowReassign(Boolean allowReassign) {
    
    
    
    this.allowReassign = allowReassign;
  }


  public DocumentSendReminderResponse apiApplicationId(String apiApplicationId) {
    
    
    
    
    this.apiApplicationId = apiApplicationId;
    return this;
  }

   /**
   * Get apiApplicationId
   * @return apiApplicationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getApiApplicationId() {
    return apiApplicationId;
  }


  public void setApiApplicationId(String apiApplicationId) {
    
    
    
    this.apiApplicationId = apiApplicationId;
  }


  public DocumentSendReminderResponse customRequesterEmail(String customRequesterEmail) {
    
    
    
    
    this.customRequesterEmail = customRequesterEmail;
    return this;
  }

   /**
   * Get customRequesterEmail
   * @return customRequesterEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "alleen.pollich@mccullough.net", value = "")

  public String getCustomRequesterEmail() {
    return customRequesterEmail;
  }


  public void setCustomRequesterEmail(String customRequesterEmail) {
    
    
    
    this.customRequesterEmail = customRequesterEmail;
  }


  public DocumentSendReminderResponse customRequesterName(String customRequesterName) {
    
    
    
    
    this.customRequesterName = customRequesterName;
    return this;
  }

   /**
   * Get customRequesterName
   * @return customRequesterName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Padme Amidala", value = "")

  public String getCustomRequesterName() {
    return customRequesterName;
  }


  public void setCustomRequesterName(String customRequesterName) {
    
    
    
    this.customRequesterName = customRequesterName;
  }


  public DocumentSendReminderResponse declineRedirectUrl(String declineRedirectUrl) {
    
    
    
    
    this.declineRedirectUrl = declineRedirectUrl;
    return this;
  }

   /**
   * Get declineRedirectUrl
   * @return declineRedirectUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "http://borer-ward.name/cleo.frami", value = "")

  public String getDeclineRedirectUrl() {
    return declineRedirectUrl;
  }


  public void setDeclineRedirectUrl(String declineRedirectUrl) {
    
    
    
    this.declineRedirectUrl = declineRedirectUrl;
  }


  public DocumentSendReminderResponse embeddedSigning(Boolean embeddedSigning) {
    
    
    
    
    this.embeddedSigning = embeddedSigning;
    return this;
  }

   /**
   * Get embeddedSigning
   * @return embeddedSigning
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getEmbeddedSigning() {
    return embeddedSigning;
  }


  public void setEmbeddedSigning(Boolean embeddedSigning) {
    
    
    
    this.embeddedSigning = embeddedSigning;
  }


  public DocumentSendReminderResponse expiresIn(Double expiresIn) {
    
    
    
    
    this.expiresIn = expiresIn;
    return this;
  }

  public DocumentSendReminderResponse expiresIn(Integer expiresIn) {
    
    
    
    
    this.expiresIn = expiresIn.doubleValue();
    return this;
  }

   /**
   * Get expiresIn
   * @return expiresIn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "")

  public Double getExpiresIn() {
    return expiresIn;
  }


  public void setExpiresIn(Double expiresIn) {
    
    
    
    this.expiresIn = expiresIn;
  }


  public DocumentSendReminderResponse metadata(DocumentSendReminderResponseMetadata metadata) {
    
    
    
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DocumentSendReminderResponseMetadata getMetadata() {
    return metadata;
  }


  public void setMetadata(DocumentSendReminderResponseMetadata metadata) {
    
    
    
    this.metadata = metadata;
  }


  public DocumentSendReminderResponse redirectUrl(String redirectUrl) {
    
    
    
    
    this.redirectUrl = redirectUrl;
    return this;
  }

   /**
   * Get redirectUrl
   * @return redirectUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "http://gottlieb.info/ray.yundt", value = "")

  public String getRedirectUrl() {
    return redirectUrl;
  }


  public void setRedirectUrl(String redirectUrl) {
    
    
    
    this.redirectUrl = redirectUrl;
  }


  public DocumentSendReminderResponse reminders(Boolean reminders) {
    
    
    
    
    this.reminders = reminders;
    return this;
  }

   /**
   * Get reminders
   * @return reminders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getReminders() {
    return reminders;
  }


  public void setReminders(Boolean reminders) {
    
    
    
    this.reminders = reminders;
  }


  public DocumentSendReminderResponse applySigningOrder(Boolean applySigningOrder) {
    
    
    
    
    this.applySigningOrder = applySigningOrder;
    return this;
  }

   /**
   * Get applySigningOrder
   * @return applySigningOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getApplySigningOrder() {
    return applySigningOrder;
  }


  public void setApplySigningOrder(Boolean applySigningOrder) {
    
    
    
    this.applySigningOrder = applySigningOrder;
  }


  public DocumentSendReminderResponse message(String message) {
    
    
    
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "<p>Hey there,</p><p>&nbsp;</p><p>Please review and complete this document. You can click on the document below to get started.</p>", value = "")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    
    
    
    this.message = message;
  }


  public DocumentSendReminderResponse subject(String subject) {
    
    
    
    
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Please complete distant-message/error.js", value = "")

  public String getSubject() {
    return subject;
  }


  public void setSubject(String subject) {
    
    
    
    this.subject = subject;
  }


  public DocumentSendReminderResponse fields(List<List<DocumentSendReminderResponseFieldsInnerInner>> fields) {
    
    
    
    
    this.fields = fields;
    return this;
  }

  public DocumentSendReminderResponse addFieldsItem(List<DocumentSendReminderResponseFieldsInnerInner> fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<List<DocumentSendReminderResponseFieldsInnerInner>> getFields() {
    return fields;
  }


  public void setFields(List<List<DocumentSendReminderResponseFieldsInnerInner>> fields) {
    
    
    
    this.fields = fields;
  }


  public DocumentSendReminderResponse files(List<DocumentSendReminderResponseFilesInner> files) {
    
    
    
    
    this.files = files;
    return this;
  }

  public DocumentSendReminderResponse addFilesItem(DocumentSendReminderResponseFilesInner filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DocumentSendReminderResponseFilesInner> getFiles() {
    return files;
  }


  public void setFiles(List<DocumentSendReminderResponseFilesInner> files) {
    
    
    
    this.files = files;
  }


  public DocumentSendReminderResponse copiedContacts(List<DocumentSendReminderResponseCopiedContactsInner> copiedContacts) {
    
    
    
    
    this.copiedContacts = copiedContacts;
    return this;
  }

  public DocumentSendReminderResponse addCopiedContactsItem(DocumentSendReminderResponseCopiedContactsInner copiedContactsItem) {
    if (this.copiedContacts == null) {
      this.copiedContacts = new ArrayList<>();
    }
    this.copiedContacts.add(copiedContactsItem);
    return this;
  }

   /**
   * Get copiedContacts
   * @return copiedContacts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DocumentSendReminderResponseCopiedContactsInner> getCopiedContacts() {
    return copiedContacts;
  }


  public void setCopiedContacts(List<DocumentSendReminderResponseCopiedContactsInner> copiedContacts) {
    
    
    
    this.copiedContacts = copiedContacts;
  }


  public DocumentSendReminderResponse recipients(List<DocumentSendReminderResponseRecipientsInner> recipients) {
    
    
    
    
    this.recipients = recipients;
    return this;
  }

  public DocumentSendReminderResponse addRecipientsItem(DocumentSendReminderResponseRecipientsInner recipientsItem) {
    if (this.recipients == null) {
      this.recipients = new ArrayList<>();
    }
    this.recipients.add(recipientsItem);
    return this;
  }

   /**
   * Get recipients
   * @return recipients
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DocumentSendReminderResponseRecipientsInner> getRecipients() {
    return recipients;
  }


  public void setRecipients(List<DocumentSendReminderResponseRecipientsInner> recipients) {
    
    
    
    this.recipients = recipients;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DocumentSendReminderResponse instance itself
   */
  public DocumentSendReminderResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentSendReminderResponse documentSendReminderResponse = (DocumentSendReminderResponse) o;
    return Objects.equals(this.id, documentSendReminderResponse.id) &&
        Objects.equals(this.archived, documentSendReminderResponse.archived) &&
        Objects.equals(this.embeddedEditUrl, documentSendReminderResponse.embeddedEditUrl) &&
        Objects.equals(this.embeddedPreviewUrl, documentSendReminderResponse.embeddedPreviewUrl) &&
        Objects.equals(this.name, documentSendReminderResponse.name) &&
        Objects.equals(this.requesterEmailAddress, documentSendReminderResponse.requesterEmailAddress) &&
        Objects.equals(this.status, documentSendReminderResponse.status) &&
        Objects.equals(this.testMode, documentSendReminderResponse.testMode) &&
        Objects.equals(this.createdAt, documentSendReminderResponse.createdAt) &&
        Objects.equals(this.updatedAt, documentSendReminderResponse.updatedAt) &&
        Objects.equals(this.errorMessage, documentSendReminderResponse.errorMessage) &&
        Objects.equals(this.declineMessage, documentSendReminderResponse.declineMessage) &&
        Objects.equals(this.allowDecline, documentSendReminderResponse.allowDecline) &&
        Objects.equals(this.allowReassign, documentSendReminderResponse.allowReassign) &&
        Objects.equals(this.apiApplicationId, documentSendReminderResponse.apiApplicationId) &&
        Objects.equals(this.customRequesterEmail, documentSendReminderResponse.customRequesterEmail) &&
        Objects.equals(this.customRequesterName, documentSendReminderResponse.customRequesterName) &&
        Objects.equals(this.declineRedirectUrl, documentSendReminderResponse.declineRedirectUrl) &&
        Objects.equals(this.embeddedSigning, documentSendReminderResponse.embeddedSigning) &&
        Objects.equals(this.expiresIn, documentSendReminderResponse.expiresIn) &&
        Objects.equals(this.metadata, documentSendReminderResponse.metadata) &&
        Objects.equals(this.redirectUrl, documentSendReminderResponse.redirectUrl) &&
        Objects.equals(this.reminders, documentSendReminderResponse.reminders) &&
        Objects.equals(this.applySigningOrder, documentSendReminderResponse.applySigningOrder) &&
        Objects.equals(this.message, documentSendReminderResponse.message) &&
        Objects.equals(this.subject, documentSendReminderResponse.subject) &&
        Objects.equals(this.fields, documentSendReminderResponse.fields) &&
        Objects.equals(this.files, documentSendReminderResponse.files) &&
        Objects.equals(this.copiedContacts, documentSendReminderResponse.copiedContacts) &&
        Objects.equals(this.recipients, documentSendReminderResponse.recipients)&&
        Objects.equals(this.additionalProperties, documentSendReminderResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, archived, embeddedEditUrl, embeddedPreviewUrl, name, requesterEmailAddress, status, testMode, createdAt, updatedAt, errorMessage, declineMessage, allowDecline, allowReassign, apiApplicationId, customRequesterEmail, customRequesterName, declineRedirectUrl, embeddedSigning, expiresIn, metadata, redirectUrl, reminders, applySigningOrder, message, subject, fields, files, copiedContacts, recipients, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentSendReminderResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    embeddedEditUrl: ").append(toIndentedString(embeddedEditUrl)).append("\n");
    sb.append("    embeddedPreviewUrl: ").append(toIndentedString(embeddedPreviewUrl)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    requesterEmailAddress: ").append(toIndentedString(requesterEmailAddress)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    testMode: ").append(toIndentedString(testMode)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    declineMessage: ").append(toIndentedString(declineMessage)).append("\n");
    sb.append("    allowDecline: ").append(toIndentedString(allowDecline)).append("\n");
    sb.append("    allowReassign: ").append(toIndentedString(allowReassign)).append("\n");
    sb.append("    apiApplicationId: ").append(toIndentedString(apiApplicationId)).append("\n");
    sb.append("    customRequesterEmail: ").append(toIndentedString(customRequesterEmail)).append("\n");
    sb.append("    customRequesterName: ").append(toIndentedString(customRequesterName)).append("\n");
    sb.append("    declineRedirectUrl: ").append(toIndentedString(declineRedirectUrl)).append("\n");
    sb.append("    embeddedSigning: ").append(toIndentedString(embeddedSigning)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    redirectUrl: ").append(toIndentedString(redirectUrl)).append("\n");
    sb.append("    reminders: ").append(toIndentedString(reminders)).append("\n");
    sb.append("    applySigningOrder: ").append(toIndentedString(applySigningOrder)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    copiedContacts: ").append(toIndentedString(copiedContacts)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("archived");
    openapiFields.add("embedded_edit_url");
    openapiFields.add("embedded_preview_url");
    openapiFields.add("name");
    openapiFields.add("requester_email_address");
    openapiFields.add("status");
    openapiFields.add("test_mode");
    openapiFields.add("created_at");
    openapiFields.add("updated_at");
    openapiFields.add("error_message");
    openapiFields.add("decline_message");
    openapiFields.add("allow_decline");
    openapiFields.add("allow_reassign");
    openapiFields.add("api_application_id");
    openapiFields.add("custom_requester_email");
    openapiFields.add("custom_requester_name");
    openapiFields.add("decline_redirect_url");
    openapiFields.add("embedded_signing");
    openapiFields.add("expires_in");
    openapiFields.add("metadata");
    openapiFields.add("redirect_url");
    openapiFields.add("reminders");
    openapiFields.add("apply_signing_order");
    openapiFields.add("message");
    openapiFields.add("subject");
    openapiFields.add("fields");
    openapiFields.add("files");
    openapiFields.add("copied_contacts");
    openapiFields.add("recipients");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DocumentSendReminderResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DocumentSendReminderResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DocumentSendReminderResponse is not found in the empty JSON string", DocumentSendReminderResponse.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("embedded_edit_url").isJsonNull() && (jsonObj.get("embedded_edit_url") != null && !jsonObj.get("embedded_edit_url").isJsonNull()) && !jsonObj.get("embedded_edit_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `embedded_edit_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("embedded_edit_url").toString()));
      }
      if ((jsonObj.get("embedded_preview_url") != null && !jsonObj.get("embedded_preview_url").isJsonNull()) && !jsonObj.get("embedded_preview_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `embedded_preview_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("embedded_preview_url").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("requester_email_address") != null && !jsonObj.get("requester_email_address").isJsonNull()) && !jsonObj.get("requester_email_address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requester_email_address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requester_email_address").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("updated_at") != null && !jsonObj.get("updated_at").isJsonNull()) && !jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
      if (!jsonObj.get("error_message").isJsonNull() && (jsonObj.get("error_message") != null && !jsonObj.get("error_message").isJsonNull()) && !jsonObj.get("error_message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error_message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error_message").toString()));
      }
      if (!jsonObj.get("decline_message").isJsonNull() && (jsonObj.get("decline_message") != null && !jsonObj.get("decline_message").isJsonNull()) && !jsonObj.get("decline_message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `decline_message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("decline_message").toString()));
      }
      if (!jsonObj.get("api_application_id").isJsonNull() && (jsonObj.get("api_application_id") != null && !jsonObj.get("api_application_id").isJsonNull()) && !jsonObj.get("api_application_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `api_application_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("api_application_id").toString()));
      }
      if ((jsonObj.get("custom_requester_email") != null && !jsonObj.get("custom_requester_email").isJsonNull()) && !jsonObj.get("custom_requester_email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `custom_requester_email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom_requester_email").toString()));
      }
      if ((jsonObj.get("custom_requester_name") != null && !jsonObj.get("custom_requester_name").isJsonNull()) && !jsonObj.get("custom_requester_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `custom_requester_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custom_requester_name").toString()));
      }
      if ((jsonObj.get("decline_redirect_url") != null && !jsonObj.get("decline_redirect_url").isJsonNull()) && !jsonObj.get("decline_redirect_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `decline_redirect_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("decline_redirect_url").toString()));
      }
      // validate the optional field `metadata`
      if (jsonObj.get("metadata") != null && !jsonObj.get("metadata").isJsonNull()) {
        DocumentSendReminderResponseMetadata.validateJsonObject(jsonObj.getAsJsonObject("metadata"));
      }
      if ((jsonObj.get("redirect_url") != null && !jsonObj.get("redirect_url").isJsonNull()) && !jsonObj.get("redirect_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `redirect_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("redirect_url").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if ((jsonObj.get("subject") != null && !jsonObj.get("subject").isJsonNull()) && !jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("fields") != null && !jsonObj.get("fields").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `fields` to be an array in the JSON string but got `%s`", jsonObj.get("fields").toString()));
      }
      if (jsonObj.get("files") != null && !jsonObj.get("files").isJsonNull()) {
        JsonArray jsonArrayfiles = jsonObj.getAsJsonArray("files");
        if (jsonArrayfiles != null) {
          // ensure the json data is an array
          if (!jsonObj.get("files").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `files` to be an array in the JSON string but got `%s`", jsonObj.get("files").toString()));
          }

          // validate the optional field `files` (array)
          for (int i = 0; i < jsonArrayfiles.size(); i++) {
            DocumentSendReminderResponseFilesInner.validateJsonObject(jsonArrayfiles.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("copied_contacts") != null && !jsonObj.get("copied_contacts").isJsonNull()) {
        JsonArray jsonArraycopiedContacts = jsonObj.getAsJsonArray("copied_contacts");
        if (jsonArraycopiedContacts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("copied_contacts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `copied_contacts` to be an array in the JSON string but got `%s`", jsonObj.get("copied_contacts").toString()));
          }

          // validate the optional field `copied_contacts` (array)
          for (int i = 0; i < jsonArraycopiedContacts.size(); i++) {
            DocumentSendReminderResponseCopiedContactsInner.validateJsonObject(jsonArraycopiedContacts.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("recipients") != null && !jsonObj.get("recipients").isJsonNull()) {
        JsonArray jsonArrayrecipients = jsonObj.getAsJsonArray("recipients");
        if (jsonArrayrecipients != null) {
          // ensure the json data is an array
          if (!jsonObj.get("recipients").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `recipients` to be an array in the JSON string but got `%s`", jsonObj.get("recipients").toString()));
          }

          // validate the optional field `recipients` (array)
          for (int i = 0; i < jsonArrayrecipients.size(); i++) {
            DocumentSendReminderResponseRecipientsInner.validateJsonObject(jsonArrayrecipients.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DocumentSendReminderResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DocumentSendReminderResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DocumentSendReminderResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DocumentSendReminderResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<DocumentSendReminderResponse>() {
           @Override
           public void write(JsonWriter out, DocumentSendReminderResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DocumentSendReminderResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DocumentSendReminderResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DocumentSendReminderResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DocumentSendReminderResponse
  * @throws IOException if the JSON string is invalid with respect to DocumentSendReminderResponse
  */
  public static DocumentSendReminderResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DocumentSendReminderResponse.class);
  }

 /**
  * Convert an instance of DocumentSendReminderResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

